FROM golang:1.25 AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o bankservice ./main.go

FROM golang:1.25-alpine
WORKDIR /app
COPY --from=build /app/bankservice .
EXPOSE 8080
CMD ["./bankservice"]