openapi: 3.0.3
info:
  title: Embedding Service API
  version: 1.0.0
  description: Service that produces embeddings for text chunks.
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: http://{host}:{port}/api/v1
    description: Internal embedding service
    variables:
      host:
        default: localhost
      port:
        default: "8083"
security: []
tags:
  - name: Embeddings
    description: Embedding generation endpoints
  - name: Health
    description: Health check

paths:
  /embed:
    post:
      tags: [Embeddings]
      summary: Generate embeddings for chunks
      operationId: embed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmbedRequest"
      responses:
        "200":
          description: Embeddings generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmbedResult"
              examples:
                multiple_results:
                  summary: Multiple embedding results
                  value:
                    model: text-search-doc
                    dimension: 256
                    embeddings:
                      - chunkId: chunk-001
                        chunkIndex: 0
                        dimension: 256
                        embedding: [0.123, -0.456, 0.789]
                      - chunkId: chunk-002
                        chunkIndex: 1
                        dimension: 256
                        embedding: [0.234, -0.567, 0.89]
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /health:
    get:
      tags: [Health]
      summary: Health check
      operationId: healthCheck
      responses:
        "200":
          description: OK
        "400":
          description: Bad request

components:
  schemas:
    EmbedRequest:
      type: object
      required: [chunks]
      properties:
        chunks:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/TextChunk"

    TextChunk:
      type: object
      required: [chunkId, text, chunkIndex]
      properties:
        chunkId:
          type: string
        text:
          type: string
        chunkIndex:
          type: integer
          minimum: 0

    EmbedResult:
      type: object
      required: [model, dimension, embeddings]
      properties:
        model:
          type: string
          description: Model actually used by the service (configured server-side).
        dimension:
          type: integer
          description: Vector dimension for the configured model.
        embeddings:
          type: array
          items:
            $ref: "#/components/schemas/ChunkEmbedding"

    ChunkEmbedding:
      type: object
      required: [chunkId, chunkIndex, dimension, embedding]
      properties:
        chunkId:
          type: string
        chunkIndex:
          type: integer
          minimum: 0
        dimension:
          type: integer
        embedding:
          type: array
          description: Embedding vector; length equals `dimension`.
          items:
            type: number
            format: double
          example: [0.123, -0.456, 0.789]

    ErrorCode:
      type: string
      enum: [BAD_REQUEST, INTERNAL_ERROR]

    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code:
          $ref: "#/components/schemas/ErrorCode"
        message:
          type: string
        details:
          type: object
          additionalProperties: true
