openapi: 3.0.3
info:
  title: File Storage Service API
  version: 1.0.0
  description: Service responsible only for storing and serving raw document files
    (upload, download, metadata).
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
- url: http://{host}:{port}/api/v1
  description: Internal file storage service
  variables:
    host:
      default: localhost
    port:
      default: '8081'
security: []
tags:
- name: Files
  description: File upload/download operations
- name: Health
  description: Health check
paths:
  /files/upload:
    post:
      tags:
      - Files
      summary: Upload a document file
      operationId: uploadFile
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadFileRequest'
            encoding:
              metadata:
                contentType: application/json
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFileResult'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /files/{fileId}:
    get:
      tags:
      - Files
      summary: Download a file
      operationId: downloadFile
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: File content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /files/{fileId}/info:
    get:
      tags:
      - Files
      summary: Get file metadata
      operationId: getFileInfo
      parameters:
      - $ref: '#/components/parameters/XRequestId'
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: File metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileInfoResponse'
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health:
    get:
      tags:
      - Health
      summary: Health check
      operationId: health
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
components:
  parameters:
    XRequestId:
      name: X-Request-Id
      in: header
      required: false
      schema:
        type: string
      description: Correlation/request id for tracing.
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: false
      schema:
        type: string
      description: Optional idempotency key to make upload retries safe.
  schemas:
    UploadFileRequest:
      type: object
      required:
      - file
      - metadata
      properties:
        file:
          type: string
          format: binary
        metadata:
          type: object
          required:
          - workId
          properties:
            workId:
              type: string
            originalFileName:
              type: string
            contentType:
              type: string
            submittedAt:
              type: string
              format: date-time
    UploadFileResult:
      type: object
      required:
      - fileId
      - storedAt
      properties:
        fileId:
          type: string
          format: uuid
        storedAt:
          type: string
          format: date-time
        checksumSha256:
          type: string
        sizeBytes:
          type: integer
          format: int64
        contentType:
          type: string
        originalFileName:
          type: string
    FileInfoResponse:
      type: object
      required:
      - fileId
      - storedAt
      properties:
        fileId:
          type: string
          format: uuid
        storedAt:
          type: string
          format: date-time
        checksumSha256:
          type: string
        sizeBytes:
          type: integer
          format: int64
        contentType:
          type: string
        originalFileName:
          type: string
    ErrorCode:
      type: string
      enum:
      - BAD_REQUEST
      - NOT_FOUND
      - PAYLOAD_TOO_LARGE
      - INTERNAL_ERROR
    ErrorResponse:
      type: object
      required:
      - code
      - message
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
        details:
          type: object
          additionalProperties: true
