// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_ops.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAccountOp = `-- name: InsertAccountOp :one
INSERT INTO account_ops (order_id, user_id, delta)
VALUES ($1, $2, $3)
    ON CONFLICT (order_id) DO NOTHING
RETURNING order_id
`

type InsertAccountOpParams struct {
	OrderID pgtype.UUID `json:"order_id"`
	UserID  string      `json:"user_id"`
	Delta   int64       `json:"delta"`
}

func (q *Queries) InsertAccountOp(ctx context.Context, arg InsertAccountOpParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAccountOp, arg.OrderID, arg.UserID, arg.Delta)
	var order_id pgtype.UUID
	err := row.Scan(&order_id)
	return order_id, err
}
