// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
)

const accountExists = `-- name: AccountExists :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE user_id = $1) AS exists
`

func (q *Queries) AccountExists(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, accountExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, balance)
VALUES ($1, 0)
    ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, balance
`

type CreateAccountRow struct {
	UserID  string `json:"user_id"`
	Balance int64  `json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, userID string) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, userID)
	var i CreateAccountRow
	err := row.Scan(&i.UserID, &i.Balance)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT balance FROM accounts WHERE user_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const topUp = `-- name: TopUp :one
UPDATE accounts
SET balance = balance + $2
WHERE user_id = $1
    RETURNING user_id, balance
`

type TopUpParams struct {
	UserID  string `json:"user_id"`
	Balance int64  `json:"balance"`
}

type TopUpRow struct {
	UserID  string `json:"user_id"`
	Balance int64  `json:"balance"`
}

func (q *Queries) TopUp(ctx context.Context, arg TopUpParams) (TopUpRow, error) {
	row := q.db.QueryRow(ctx, topUp, arg.UserID, arg.Balance)
	var i TopUpRow
	err := row.Scan(&i.UserID, &i.Balance)
	return i, err
}
