// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertInboxCheck = `-- name: InsertInboxCheck :one
WITH ins AS (
INSERT INTO inbox (message_id, order_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
    RETURNING 1 AS inserted
    )
SELECT COALESCE((SELECT inserted FROM ins), 0)::bigint AS inserted
`

type InsertInboxCheckParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	OrderID   pgtype.UUID `json:"order_id"`
}

func (q *Queries) InsertInboxCheck(ctx context.Context, arg InsertInboxCheckParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertInboxCheck, arg.MessageID, arg.OrderID)
	var inserted int64
	err := row.Scan(&inserted)
	return inserted, err
}
