// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	UserID    string             `json:"user_id"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AccountOp struct {
	OrderID   pgtype.UUID        `json:"order_id"`
	UserID    string             `json:"user_id"`
	Delta     int64              `json:"delta"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Inbox struct {
	MessageID   pgtype.UUID        `json:"message_id"`
	OrderID     pgtype.UUID        `json:"order_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Outbox struct {
	ID        int64              `json:"id"`
	Topic     string             `json:"topic"`
	KafkaKey  string             `json:"kafka_key"`
	Payload   []byte             `json:"payload"`
	Status    string             `json:"status"`
	Attempts  int32              `json:"attempts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	LastError pgtype.Text        `json:"last_error"`
}
