// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topup_idempotency.sql

package db

import (
	"context"
)

const deleteTopupIdempotency = `-- name: DeleteTopupIdempotency :exec
DELETE FROM topup_idempotency
WHERE user_id = $1 AND idempotency_key = $2
`

type DeleteTopupIdempotencyParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) DeleteTopupIdempotency(ctx context.Context, arg DeleteTopupIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteTopupIdempotency, arg.UserID, arg.IdempotencyKey)
	return err
}

const getTopupIdempotency = `-- name: GetTopupIdempotency :one
SELECT user_id, idempotency_key, amount, balance_after
FROM topup_idempotency
WHERE user_id = $1 AND idempotency_key = $2
`

type GetTopupIdempotencyParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetTopupIdempotencyRow struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
	Amount         int64  `json:"amount"`
	BalanceAfter   int64  `json:"balance_after"`
}

func (q *Queries) GetTopupIdempotency(ctx context.Context, arg GetTopupIdempotencyParams) (GetTopupIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getTopupIdempotency, arg.UserID, arg.IdempotencyKey)
	var i GetTopupIdempotencyRow
	err := row.Scan(
		&i.UserID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.BalanceAfter,
	)
	return i, err
}

const insertTopupIdempotency = `-- name: InsertTopupIdempotency :one
WITH ins AS (
INSERT INTO topup_idempotency (user_id, idempotency_key, amount, balance_after)
VALUES ($1, $2, $3, 0)
ON CONFLICT (user_id, idempotency_key) DO NOTHING
    RETURNING 1 AS inserted
    )
SELECT COALESCE((SELECT inserted FROM ins), 0)::bigint AS inserted
`

type InsertTopupIdempotencyParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
	Amount         int64  `json:"amount"`
}

func (q *Queries) InsertTopupIdempotency(ctx context.Context, arg InsertTopupIdempotencyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTopupIdempotency, arg.UserID, arg.IdempotencyKey, arg.Amount)
	var inserted int64
	err := row.Scan(&inserted)
	return inserted, err
}

const setTopupIdempotencyBalance = `-- name: SetTopupIdempotencyBalance :one
UPDATE topup_idempotency
SET balance_after = $3
WHERE user_id = $1 AND idempotency_key = $2
RETURNING balance_after
`

type SetTopupIdempotencyBalanceParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
	BalanceAfter   int64  `json:"balance_after"`
}

func (q *Queries) SetTopupIdempotencyBalance(ctx context.Context, arg SetTopupIdempotencyBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, setTopupIdempotencyBalance, arg.UserID, arg.IdempotencyKey, arg.BalanceAfter)
	var balance_after int64
	err := row.Scan(&balance_after)
	return balance_after, err
}
