openapi: 3.0.3
info:
  title: Gozon API Gateway
  version: 1.0.0
  description: >
    API Gateway routes HTTP requests to Orders and Payments via gRPC.

    Header X-User-Id is optional for most endpoints: if missing, gateway generates user_id and returns it in response body.
    For GET /payments/account/balance header X-User-Id is REQUIRED.
  license:
    name: MIT
    url: https://opensource.org/license/mit/

servers:
  - url: http://{host}:{port}/api/v1
    description: Local/dev server
    variables:
      host:
        default: localhost
      port:
        default: "8080"

# Root-level security is explicitly defined to satisfy linters.
# Most operations do not require auth, except where overridden per-operation.
security: []

tags:
  - name: Payments
    description: Operations for account creation, top-up and balance.
  - name: Orders
    description: Operations for creating orders, listing and fetching order status.

components:
  securitySchemes:
    UserIdHeaderAuth:
      type: apiKey
      in: header
      name: X-User-Id
      description: User identifier provided via X-User-Id header.

  parameters:
    UserIdHeader:
      name: X-User-Id
      in: header
      required: false
      description: Optional user identifier. If missing, gateway generates a new user_id.
      schema:
        type: string
        minLength: 1

    UserIdHeaderRequired:
      name: X-User-Id
      in: header
      required: true
      description: Required user identifier for this endpoint.
      schema:
        type: string
        minLength: 1

    IdempotencyKeyHeader:
      name: Idempotency-Key
      in: header
      required: false
      description: Optional idempotency key for safe retries of POST requests.
      schema:
        type: string
        minLength: 1

    OrderIdPath:
      name: orderId
      in: path
      required: true
      schema:
        type: string
        minLength: 1

    LimitQuery:
      name: limit
      in: query
      required: false
      description: Max number of orders to return.
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 200
        default: 50

    PageTokenQuery:
      name: page_token
      in: query
      required: false
      description: Pagination token returned by previous request.
      schema:
        type: string
        minLength: 1

  schemas:
    ErrorResponse:
      type: object
      required: [error]
      properties:
        user_id:
          type: string
          description: Resolved user id (provided or generated by gateway), if available.
        error:
          type: string
        details:
          type: object
          additionalProperties: true

    OrderStatus:
      type: string
      enum: [NEW, FINISHED, CANCELLED]

    Order:
      type: object
      required: [order_id, user_id, amount, description, status]
      properties:
        order_id:
          type: string
        user_id:
          type: string
        amount:
          type: integer
          format: int64
          minimum: 1
          description: Amount in minimal currency units (e.g. cents/kopecks).
        description:
          type: string
        status:
          $ref: "#/components/schemas/OrderStatus"
        created_at:
          type: string
          format: date-time

    # ===== Payments: /payments/account =====
    CreateAccountRequest:
      type: object
      description: >
        Empty request body. user_id is taken from X-User-Id header, or generated by gateway if missing.
      additionalProperties: false

    CreateAccountResponse:
      type: object
      required: [user_id, balance]
      properties:
        user_id:
          type: string
          description: Resolved user id (provided or generated by gateway).
        balance:
          type: integer
          format: int64
          minimum: 0

    # ===== Payments: /payments/account/topup =====
    TopUpAccountRequest:
      type: object
      required: [amount]
      additionalProperties: false
      properties:
        amount:
          type: integer
          format: int64
          minimum: 1
          description: Amount in minimal currency units (e.g. cents/kopecks).

    TopUpAccountResponse:
      type: object
      required: [user_id, balance]
      properties:
        user_id:
          type: string
          description: Resolved user id (provided or generated by gateway).
        balance:
          type: integer
          format: int64
          minimum: 0

    GetBalanceResponse:
      type: object
      required: [user_id, balance]
      properties:
        user_id:
          type: string
          description: User id from request header.
        balance:
          type: integer
          format: int64
          minimum: 0

    # ===== Orders: /orders =====
    CreateOrderRequest:
      type: object
      required: [amount, description]
      additionalProperties: false
      properties:
        amount:
          type: integer
          format: int64
          minimum: 1
        description:
          type: string
          minLength: 1

    CreateOrderResponse:
      type: object
      required: [user_id, order]
      properties:
        user_id:
          type: string
          description: Resolved user id (provided or generated by gateway).
        order:
          $ref: "#/components/schemas/Order"

    ListOrdersResponse:
      type: object
      required: [user_id, orders]
      properties:
        user_id:
          type: string
          description: Resolved user id (provided or generated by gateway).
        orders:
          type: array
          items:
            $ref: "#/components/schemas/Order"

    GetOrderResponse:
      type: object
      required: [user_id, order]
      properties:
        user_id:
          type: string
          description: Resolved user id (provided or generated by gateway).
        order:
          $ref: "#/components/schemas/Order"

paths:
  /payments/account:
    post:
      tags: [Payments]
      summary: Create account (max 1 per user)
      operationId: createAccount
      description: Creates a new account for the user. If account already exists, returns conflict.
      parameters:
        - $ref: "#/components/parameters/UserIdHeader"
        - $ref: "#/components/parameters/IdempotencyKeyHeader"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccountRequest"
      responses:
        "201":
          description: Account created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAccountResponse"
        "409":
          description: Account already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /payments/account/topup:
    post:
      tags: [Payments]
      summary: Top up account
      operationId: topUpAccount
      parameters:
        - $ref: "#/components/parameters/UserIdHeader"
        - $ref: "#/components/parameters/IdempotencyKeyHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TopUpAccountRequest"
      responses:
        "200":
          description: Account topped up
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopUpAccountResponse"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /payments/account/balance:
    get:
      tags: [Payments]
      summary: Get account balance
      operationId: getBalance
      description: X-User-Id header is required for this endpoint.
      # Override root security: this endpoint requires X-User-Id as "auth"
      security:
        - UserIdHeaderAuth: []
      parameters:
        - $ref: "#/components/parameters/UserIdHeaderRequired"
      responses:
        "200":
          description: Balance returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBalanceResponse"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Missing or invalid X-User-Id header
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /orders:
    post:
      tags: [Orders]
      summary: Create order (async payment starts)
      operationId: createOrder
      description: >
        Creates a new order with status NEW and asynchronously starts payment process.
        Order status later becomes FINISHED or CANCELLED.
      parameters:
        - $ref: "#/components/parameters/UserIdHeader"
        - $ref: "#/components/parameters/IdempotencyKeyHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        "201":
          description: Order created (payment started asynchronously)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateOrderResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    get:
      tags: [Orders]
      summary: List orders
      operationId: listOrders
      parameters:
        - $ref: "#/components/parameters/UserIdHeader"
        - $ref: "#/components/parameters/LimitQuery"
        - $ref: "#/components/parameters/PageTokenQuery"
      responses:
        "200":
          description: Orders list returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOrdersResponse"
        "400":
          description: Bad request (invalid query params)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /orders/{orderId}:
    get:
      tags: [Orders]
      summary: Get order status/details
      operationId: getOrder
      parameters:
        - $ref: "#/components/parameters/UserIdHeader"
        - $ref: "#/components/parameters/OrderIdPath"
      responses:
        "200":
          description: Order returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderResponse"
        "404":
          description: Order not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
