// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ReportSummaryStatus.
const (
	ReportSummaryStatusDONE    ReportSummaryStatus = "DONE"
	ReportSummaryStatusERROR   ReportSummaryStatus = "ERROR"
	ReportSummaryStatusPENDING ReportSummaryStatus = "PENDING"
)

// Defines values for SubmissionCreatedResponseStatus.
const (
	SubmissionCreatedResponseStatusDONE    SubmissionCreatedResponseStatus = "DONE"
	SubmissionCreatedResponseStatusERROR   SubmissionCreatedResponseStatus = "ERROR"
	SubmissionCreatedResponseStatusPENDING SubmissionCreatedResponseStatus = "PENDING"
)

// Defines values for WorkAnalyticsItemStatus.
const (
	DONE    WorkAnalyticsItemStatus = "DONE"
	ERROR   WorkAnalyticsItemStatus = "ERROR"
	PENDING WorkAnalyticsItemStatus = "PENDING"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ReportSummary defines model for ReportSummary.
type ReportSummary struct {
	PlagiarismDetected bool                `json:"plagiarismDetected"`
	SimilarityPercent  float32             `json:"similarityPercent"`
	Status             ReportSummaryStatus `json:"status"`
}

// ReportSummaryStatus defines model for ReportSummary.Status.
type ReportSummaryStatus string

// SubmissionCreatedResponse defines model for SubmissionCreatedResponse.
type SubmissionCreatedResponse struct {
	Status       SubmissionCreatedResponseStatus `json:"status"`
	StudentId    string                          `json:"studentId"`
	SubmissionId string                          `json:"submissionId"`
	UploadedAt   time.Time                       `json:"uploadedAt"`
	WorkId       string                          `json:"workId"`
}

// SubmissionCreatedResponseStatus defines model for SubmissionCreatedResponse.Status.
type SubmissionCreatedResponseStatus string

// SubmissionDetail defines model for SubmissionDetail.
type SubmissionDetail struct {
	// FileUrl URL for file download
	FileUrl      string         `json:"fileUrl"`
	LastReport   *ReportSummary `json:"lastReport,omitempty"`
	StudentId    string         `json:"studentId"`
	SubmissionId string         `json:"submissionId"`
	UploadedAt   time.Time      `json:"uploadedAt"`
	WorkId       string         `json:"workId"`
}

// WorkAnalyticsItem defines model for WorkAnalyticsItem.
type WorkAnalyticsItem struct {
	CreatedAt          time.Time               `json:"createdAt"`
	PlagiarismDetected bool                    `json:"plagiarismDetected"`
	ReportId           string                  `json:"reportId"`
	SimilarityPercent  float32                 `json:"similarityPercent"`
	Status             WorkAnalyticsItemStatus `json:"status"`
	StudentId          string                  `json:"studentId"`
	SubmissionId       string                  `json:"submissionId"`
}

// WorkAnalyticsItemStatus defines model for WorkAnalyticsItem.Status.
type WorkAnalyticsItemStatus string

// WorkCreateRequest defines model for WorkCreateRequest.
type WorkCreateRequest struct {
	// Description Work description
	Description string `json:"description"`

	// Name Work name
	Name string `json:"name"`

	// WorkId Unique work identifier
	WorkId string `json:"workId"`
}

// WorkResponse defines model for WorkResponse.
type WorkResponse struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description string    `json:"description"`
	Name        string    `json:"name"`
	WorkId      string    `json:"workId"`
}

// WorkStats defines model for WorkStats.
type WorkStats struct {
	AverageSimilarityPercent     float32    `json:"averageSimilarityPercent"`
	LastSubmissionAt             *time.Time `json:"lastSubmissionAt"`
	SubmissionsWithPlagiarism    int        `json:"submissionsWithPlagiarism"`
	SubmissionsWithoutPlagiarism int        `json:"submissionsWithoutPlagiarism"`
	TotalSubmissions             int        `json:"totalSubmissions"`
	UniqueStudents               int        `json:"uniqueStudents"`
	WorkId                       string     `json:"workId"`
}

// PostWorksWorkIdSubmissionsMultipartBody defines parameters for PostWorksWorkIdSubmissions.
type PostWorksWorkIdSubmissionsMultipartBody struct {
	// File Work file (PDF/DOCX/ZIP)
	File openapi_types.File `json:"file"`

	// StudentId Student identifier
	StudentId string `json:"studentId"`
}

// PostWorksJSONRequestBody defines body for PostWorks for application/json ContentType.
type PostWorksJSONRequestBody = WorkCreateRequest

// PostWorksWorkIdSubmissionsMultipartRequestBody defines body for PostWorksWorkIdSubmissions for multipart/form-data ContentType.
type PostWorksWorkIdSubmissionsMultipartRequestBody PostWorksWorkIdSubmissionsMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get submission details
	// (GET /submissions/{submissionId})
	GetSubmissionsSubmissionId(w http.ResponseWriter, r *http.Request, submissionId string)
	// Create a work
	// (POST /works)
	PostWorks(w http.ResponseWriter, r *http.Request)
	// Get analytics by workId
	// (GET /works/{workId}/reports)
	GetWorksWorkIdReports(w http.ResponseWriter, r *http.Request, workId string)
	// Get statistics by workId
	// (GET /works/{workId}/stats)
	GetWorksWorkIdStats(w http.ResponseWriter, r *http.Request, workId string)
	// Submit work for review
	// (POST /works/{workId}/submissions)
	PostWorksWorkIdSubmissions(w http.ResponseWriter, r *http.Request, workId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get submission details
// (GET /submissions/{submissionId})
func (_ Unimplemented) GetSubmissionsSubmissionId(w http.ResponseWriter, r *http.Request, submissionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a work
// (POST /works)
func (_ Unimplemented) PostWorks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get analytics by workId
// (GET /works/{workId}/reports)
func (_ Unimplemented) GetWorksWorkIdReports(w http.ResponseWriter, r *http.Request, workId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get statistics by workId
// (GET /works/{workId}/stats)
func (_ Unimplemented) GetWorksWorkIdStats(w http.ResponseWriter, r *http.Request, workId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit work for review
// (POST /works/{workId}/submissions)
func (_ Unimplemented) PostWorksWorkIdSubmissions(w http.ResponseWriter, r *http.Request, workId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSubmissionsSubmissionId operation middleware
func (siw *ServerInterfaceWrapper) GetSubmissionsSubmissionId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "submissionId" -------------
	var submissionId string

	err = runtime.BindStyledParameterWithOptions("simple", "submissionId", chi.URLParam(r, "submissionId"), &submissionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "submissionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubmissionsSubmissionId(w, r, submissionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWorks operation middleware
func (siw *ServerInterfaceWrapper) PostWorks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWorks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorksWorkIdReports operation middleware
func (siw *ServerInterfaceWrapper) GetWorksWorkIdReports(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameterWithOptions("simple", "workId", chi.URLParam(r, "workId"), &workId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorksWorkIdReports(w, r, workId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorksWorkIdStats operation middleware
func (siw *ServerInterfaceWrapper) GetWorksWorkIdStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameterWithOptions("simple", "workId", chi.URLParam(r, "workId"), &workId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorksWorkIdStats(w, r, workId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWorksWorkIdSubmissions operation middleware
func (siw *ServerInterfaceWrapper) PostWorksWorkIdSubmissions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameterWithOptions("simple", "workId", chi.URLParam(r, "workId"), &workId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWorksWorkIdSubmissions(w, r, workId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/submissions/{submissionId}", wrapper.GetSubmissionsSubmissionId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/works", wrapper.PostWorks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/works/{workId}/reports", wrapper.GetWorksWorkIdReports)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/works/{workId}/stats", wrapper.GetWorksWorkIdStats)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/works/{workId}/submissions", wrapper.PostWorksWorkIdSubmissions)
	})

	return r
}
