// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertInboxCheck = `-- name: InsertInboxCheck :one
WITH ins AS (
INSERT INTO inbox (message_id)
VALUES ($1)
ON CONFLICT (message_id) DO NOTHING
    RETURNING 1 AS inserted
    )
SELECT COALESCE((SELECT inserted FROM ins), 0) AS inserted
`

func (q *Queries) InsertInboxCheck(ctx context.Context, messageID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, insertInboxCheck, messageID)
	var inserted interface{}
	err := row.Scan(&inserted)
	return inserted, err
}
