// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inbox struct {
	MessageID   pgtype.UUID        `json:"message_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Order struct {
	OrderID     pgtype.UUID        `json:"order_id"`
	UserID      string             `json:"user_id"`
	Amount      int64              `json:"amount"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID        int64              `json:"id"`
	Topic     string             `json:"topic"`
	KafkaKey  string             `json:"kafka_key"`
	Payload   []byte             `json:"payload"`
	Status    string             `json:"status"`
	Attempts  int32              `json:"attempts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	LastError pgtype.Text        `json:"last_error"`
}
