// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, amount, description, status)
VALUES ($1, $2, $3, 'NEW')
    RETURNING order_id, user_id, amount, description, status, created_at
`

type CreateOrderParams struct {
	UserID      string `json:"user_id"`
	Amount      int64  `json:"amount"`
	Description string `json:"description"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.Amount, arg.Description)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT order_id, user_id, amount, description, status, created_at
FROM orders
WHERE order_id = $1 AND user_id = $2
`

type GetOrderParams struct {
	OrderID pgtype.UUID `json:"order_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.OrderID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT order_id, user_id, amount, description, status, created_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC, order_id DESC
    LIMIT $2 OFFSET $3
`

type ListOrdersParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatusIfNew = `-- name: UpdateOrderStatusIfNew :exec
UPDATE orders
SET status = $2
WHERE order_id = $1 AND status = 'NEW'
`

type UpdateOrderStatusIfNewParams struct {
	OrderID pgtype.UUID `json:"order_id"`
	Status  string      `json:"status"`
}

// Важно для consumer: обновляем статус только если он ещё NEW (идемпотентно)
func (q *Queries) UpdateOrderStatusIfNew(ctx context.Context, arg UpdateOrderStatusIfNewParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatusIfNew, arg.OrderID, arg.Status)
	return err
}
