// Package fileanalysis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package fileanalysis

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AnalyzeResponseStatus.
const (
	AnalyzeResponseStatusQUEUED AnalyzeResponseStatus = "QUEUED"
)

// Defines values for ErrorCode.
const (
	FILENOTFOUND       ErrorCode = "FILE_NOT_FOUND"
	INTERNALERROR      ErrorCode = "INTERNAL_ERROR"
	REPORTNOTFOUND     ErrorCode = "REPORT_NOT_FOUND"
	SERVICEUNAVAILABLE ErrorCode = "SERVICE_UNAVAILABLE"
	VALIDATIONERROR    ErrorCode = "VALIDATION_ERROR"
	WORKNOTFOUND       ErrorCode = "WORK_NOT_FOUND"
)

// Defines values for ReportResponseStatus.
const (
	ReportResponseStatusDONE       ReportResponseStatus = "DONE"
	ReportResponseStatusERROR      ReportResponseStatus = "ERROR"
	ReportResponseStatusPROCESSING ReportResponseStatus = "PROCESSING"
	ReportResponseStatusQUEUED     ReportResponseStatus = "QUEUED"
)

// Defines values for WorkReportItemStatus.
const (
	DONE       WorkReportItemStatus = "DONE"
	ERROR      WorkReportItemStatus = "ERROR"
	PROCESSING WorkReportItemStatus = "PROCESSING"
	QUEUED     WorkReportItemStatus = "QUEUED"
)

// AnalyzeRequest defines model for AnalyzeRequest.
type AnalyzeRequest struct {
	// FileId File ID from file-storing service
	FileId openapi_types.UUID `json:"fileId"`

	// SubmissionId Unique submission identifier
	SubmissionId string `json:"submissionId"`

	// WorkId Work identifier (embeddings are grouped by workId)
	WorkId string `json:"workId"`
}

// AnalyzeResponse defines model for AnalyzeResponse.
type AnalyzeResponse struct {
	// Message Human-readable message
	Message *string `json:"message,omitempty"`

	// QueuedAt Timestamp when queued
	QueuedAt time.Time `json:"queuedAt"`

	// Status Initial status
	Status AnalyzeResponseStatus `json:"status"`

	// SubmissionId Submission identifier
	SubmissionId string `json:"submissionId"`

	// WorkId Work identifier
	WorkId string `json:"workId"`
}

// AnalyzeResponseStatus Initial status
type AnalyzeResponseStatus string

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code ErrorCode `json:"code"`

	// Details Additional error context
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// MatchedSubmission defines model for MatchedSubmission.
type MatchedSubmission struct {
	// MatchedChunks Number of chunks that matched
	MatchedChunks int `json:"matchedChunks"`

	// SimilarityPercent Similarity percentage with this submission
	SimilarityPercent float64 `json:"similarityPercent"`

	// SubmissionId ID of matched submission
	SubmissionId string `json:"submissionId"`
}

// ReportResponse defines model for ReportResponse.
type ReportResponse struct {
	// CompletedAt Timestamp when analysis completed (only for DONE status)
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// CreatedAt Timestamp when report was created
	CreatedAt time.Time `json:"createdAt"`

	// ErrorMessage Error message (only for ERROR status)
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// MatchedSubmissions List of submissions with high similarity
	MatchedSubmissions *[]MatchedSubmission `json:"matchedSubmissions,omitempty"`

	// PlagiarismDetected True if similarityPercent > 50%
	PlagiarismDetected bool `json:"plagiarismDetected"`

	// SimilarityPercent Similarity percentage (0-100)
	SimilarityPercent float32 `json:"similarityPercent"`

	// Status Current analysis status
	Status ReportResponseStatus `json:"status"`

	// SubmissionId Submission identifier
	SubmissionId string `json:"submissionId"`

	// WorkId Work identifier
	WorkId string `json:"workId"`
}

// ReportResponseStatus Current analysis status
type ReportResponseStatus string

// WorkReportItem defines model for WorkReportItem.
type WorkReportItem struct {
	CompletedAt        *time.Time           `json:"completedAt,omitempty"`
	CreatedAt          time.Time            `json:"createdAt"`
	PlagiarismDetected bool                 `json:"plagiarismDetected"`
	SimilarityPercent  float32              `json:"similarityPercent"`
	Status             WorkReportItemStatus `json:"status"`
	SubmissionId       string               `json:"submissionId"`
}

// WorkReportItemStatus defines model for WorkReportItem.Status.
type WorkReportItemStatus string

// WorkReportsResponse defines model for WorkReportsResponse.
type WorkReportsResponse = []WorkReportItem

// AnalyzeFileJSONRequestBody defines body for AnalyzeFile for application/json ContentType.
type AnalyzeFileJSONRequestBody = AnalyzeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AnalyzeFileWithBody request with any body
	AnalyzeFileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AnalyzeFile(ctx context.Context, body AnalyzeFileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReport request
	GetReport(ctx context.Context, submissionId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWorkReports request
	GetWorkReports(ctx context.Context, workId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AnalyzeFileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAnalyzeFileRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AnalyzeFile(ctx context.Context, body AnalyzeFileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAnalyzeFileRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReport(ctx context.Context, submissionId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReportRequest(c.Server, submissionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWorkReports(ctx context.Context, workId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkReportsRequest(c.Server, workId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAnalyzeFileRequest calls the generic AnalyzeFile builder with application/json body
func NewAnalyzeFileRequest(server string, body AnalyzeFileJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAnalyzeFileRequestWithBody(server, "application/json", bodyReader)
}

// NewAnalyzeFileRequestWithBody generates requests for AnalyzeFile with any type of body
func NewAnalyzeFileRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/analyze")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetReportRequest generates requests for GetReport
func NewGetReportRequest(server string, submissionId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "submissionId", runtime.ParamLocationPath, submissionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reports/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWorkReportsRequest generates requests for GetWorkReports
func NewGetWorkReportsRequest(server string, workId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "workId", runtime.ParamLocationPath, workId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/reports", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AnalyzeFileWithBodyWithResponse request with any body
	AnalyzeFileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnalyzeFileResponse, error)

	AnalyzeFileWithResponse(ctx context.Context, body AnalyzeFileJSONRequestBody, reqEditors ...RequestEditorFn) (*AnalyzeFileResponse, error)

	// GetReportWithResponse request
	GetReportWithResponse(ctx context.Context, submissionId string, reqEditors ...RequestEditorFn) (*GetReportResponse, error)

	// GetWorkReportsWithResponse request
	GetWorkReportsWithResponse(ctx context.Context, workId string, reqEditors ...RequestEditorFn) (*GetWorkReportsResponse, error)
}

type AnalyzeFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *AnalyzeResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r AnalyzeFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AnalyzeFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetReportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReportResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetReportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWorkReportsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WorkReportsResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetWorkReportsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkReportsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AnalyzeFileWithBodyWithResponse request with arbitrary body returning *AnalyzeFileResponse
func (c *ClientWithResponses) AnalyzeFileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnalyzeFileResponse, error) {
	rsp, err := c.AnalyzeFileWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnalyzeFileResponse(rsp)
}

func (c *ClientWithResponses) AnalyzeFileWithResponse(ctx context.Context, body AnalyzeFileJSONRequestBody, reqEditors ...RequestEditorFn) (*AnalyzeFileResponse, error) {
	rsp, err := c.AnalyzeFile(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnalyzeFileResponse(rsp)
}

// GetReportWithResponse request returning *GetReportResponse
func (c *ClientWithResponses) GetReportWithResponse(ctx context.Context, submissionId string, reqEditors ...RequestEditorFn) (*GetReportResponse, error) {
	rsp, err := c.GetReport(ctx, submissionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReportResponse(rsp)
}

// GetWorkReportsWithResponse request returning *GetWorkReportsResponse
func (c *ClientWithResponses) GetWorkReportsWithResponse(ctx context.Context, workId string, reqEditors ...RequestEditorFn) (*GetWorkReportsResponse, error) {
	rsp, err := c.GetWorkReports(ctx, workId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkReportsResponse(rsp)
}

// ParseAnalyzeFileResponse parses an HTTP response from a AnalyzeFileWithResponse call
func ParseAnalyzeFileResponse(rsp *http.Response) (*AnalyzeFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AnalyzeFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest AnalyzeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetReportResponse parses an HTTP response from a GetReportWithResponse call
func ParseGetReportResponse(rsp *http.Response) (*GetReportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReportResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetWorkReportsResponse parses an HTTP response from a GetWorkReportsWithResponse call
func ParseGetWorkReportsResponse(rsp *http.Response) (*GetWorkReportsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkReportsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WorkReportsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
